/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n';

export const KEYBOARD_LAYOUTS = [
	{
		label: __( 'QWERTY 1', 'piano-block' ),
		value: 'qwerty-1',
		keys: [
			{ note: 'C', octave: 3, isBlackKey: false, name: [ 'z' ] },
			{ note: 'C#', octave: 3, isBlackKey: true, name: [ 's' ] },
			{ note: 'D', octave: 3, isBlackKey: false, name: [ 'x' ] },
			{ note: 'D#', octave: 3, isBlackKey: true, name: [ 'd' ] },
			{ note: 'E', octave: 3, isBlackKey: false, name: [ 'c' ] },
			{ note: 'F', octave: 3, isBlackKey: false, name: [ 'v' ] },
			{ note: 'F#', octave: 3, isBlackKey: true, name: [ 'g' ] },
			{ note: 'G', octave: 3, isBlackKey: false, name: [ 'b' ] },
			{ note: 'G#', octave: 3, isBlackKey: true, name: [ 'h' ] },
			{ note: 'A', octave: 3, isBlackKey: false, name: [ 'n' ] },
			{ note: 'A#', octave: 3, isBlackKey: true, name: [ 'j' ] },
			{ note: 'B', octave: 3, isBlackKey: false, name: [ 'm' ] },
			{ note: 'C', octave: 4, isBlackKey: false, name: [ ',', 'q' ] },
			{ note: 'C#', octave: 4, isBlackKey: true, name: [ 'l', '2' ] },
			{ note: 'D', octave: 4, isBlackKey: false, name: [ '.', 'w' ] },
			{ note: 'D#', octave: 4, isBlackKey: true, name: [ '3' ] },
			{ note: 'E', octave: 4, isBlackKey: false, name: [ 'e' ] },
			{ note: 'F', octave: 4, isBlackKey: false, name: [ 'r' ] },
			{ note: 'F#', octave: 4, isBlackKey: true, name: [ '5' ] },
			{ note: 'G', octave: 4, isBlackKey: false, name: [ 't' ] },
			{ note: 'G#', octave: 4, isBlackKey: true, name: [ '6' ] },
			{ note: 'A', octave: 4, isBlackKey: false, name: [ 'y' ] },
			{ note: 'A#', octave: 4, isBlackKey: true, name: [ '7' ] },
			{ note: 'B', octave: 4, isBlackKey: false, name: [ 'u' ] },
			{ note: 'C', octave: 5, isBlackKey: false, name: [ 'i' ] },
			{ note: 'C#', octave: 5, isBlackKey: true, name: [ '9' ] },
			{ note: 'D', octave: 5, isBlackKey: false, name: [ 'o' ] },
			{ note: 'D#', octave: 5, isBlackKey: true, name: [ '0' ] },
			{ note: 'E', octave: 5, isBlackKey: false, name: [ 'p' ] },
		],
	},
	{
		label: __( 'QWERTY 2', 'piano-block' ),
		value: 'qwerty-2',
		keys: [
			{ note: 'C', octave: 3, isBlackKey: false, name: [ 'z' ] },
			{ note: 'C#', octave: 3, isBlackKey: true, name: [ 's' ] },
			{ note: 'D', octave: 3, isBlackKey: false, name: [ 'x' ] },
			{ note: 'D#', octave: 3, isBlackKey: true, name: [ 'd' ] },
			{ note: 'E', octave: 3, isBlackKey: false, name: [ 'c' ] },
			{ note: 'F', octave: 3, isBlackKey: false, name: [ 'v' ] },
			{ note: 'F#', octave: 3, isBlackKey: true, name: [ 'g' ] },
			{ note: 'G', octave: 3, isBlackKey: false, name: [ 'b' ] },
			{ note: 'G#', octave: 3, isBlackKey: true, name: [ 'h' ] },
			{ note: 'A', octave: 3, isBlackKey: false, name: [ 'n' ] },
			{ note: 'A#', octave: 3, isBlackKey: true, name: [ 'j' ] },
			{ note: 'B', octave: 3, isBlackKey: false, name: [ 'm' ] },
			{ note: 'C', octave: 4, isBlackKey: false, name: [ ',', 'q' ] },
			{ note: 'C#', octave: 4, isBlackKey: true, name: [ 'l', '1' ] },
			{ note: 'D', octave: 4, isBlackKey: false, name: [ '.', 'w' ] },
			{ note: 'D#', octave: 4, isBlackKey: true, name: [ '2' ] },
			{ note: 'E', octave: 4, isBlackKey: false, name: [ 'e' ] },
			{ note: 'F', octave: 4, isBlackKey: false, name: [ 'r' ] },
			{ note: 'F#', octave: 4, isBlackKey: true, name: [ '4' ] },
			{ note: 'G', octave: 4, isBlackKey: false, name: [ 't' ] },
			{ note: 'G#', octave: 4, isBlackKey: true, name: [ '5' ] },
			{ note: 'A', octave: 4, isBlackKey: false, name: [ 'y' ] },
			{ note: 'A#', octave: 4, isBlackKey: true, name: [ '6' ] },
			{ note: 'B', octave: 4, isBlackKey: false, name: [ 'u' ] },
			{ note: 'C', octave: 5, isBlackKey: false, name: [ 'i' ] },
			{ note: 'C#', octave: 5, isBlackKey: true, name: [ '8' ] },
			{ note: 'D', octave: 5, isBlackKey: false, name: [ 'o' ] },
			{ note: 'D#', octave: 5, isBlackKey: true, name: [ '9' ] },
			{ note: 'E', octave: 5, isBlackKey: false, name: [ 'p' ] },
		],
	},
	{
		label: __( 'AZERTY 1', 'piano-block' ),
		value: 'azerty-1',
		keys: [
			{ note: 'C', octave: 3, isBlackKey: false, name: [ '<' ] },
			{ note: 'C#', octave: 3, isBlackKey: true, name: [ 'q' ] },
			{ note: 'D', octave: 3, isBlackKey: false, name: [ 'w' ] },
			{ note: 'D#', octave: 3, isBlackKey: true, name: [ 's' ] },
			{ note: 'E', octave: 3, isBlackKey: false, name: [ 'x' ] },
			{ note: 'F', octave: 3, isBlackKey: false, name: [ 'c' ] },
			{ note: 'F#', octave: 3, isBlackKey: true, name: [ 'f' ] },
			{ note: 'G', octave: 3, isBlackKey: false, name: [ 'v' ] },
			{ note: 'G#', octave: 3, isBlackKey: true, name: [ 'g' ] },
			{ note: 'A', octave: 3, isBlackKey: false, name: [ 'b' ] },
			{ note: 'A#', octave: 3, isBlackKey: true, name: [ 'h' ] },
			{ note: 'B', octave: 3, isBlackKey: false, name: [ 'n' ] },
			{ note: 'C', octave: 4, isBlackKey: false, name: [ ',', 'a' ] },
			{ note: 'C#', octave: 4, isBlackKey: true, name: [ 'k', '&' ] },
			{ note: 'D', octave: 4, isBlackKey: false, name: [ ';', 'z' ] },
			{ note: 'D#', octave: 4, isBlackKey: true, name: [ 'é' ] },
			{ note: 'E', octave: 4, isBlackKey: false, name: [ 'e' ] },
			{ note: 'F', octave: 4, isBlackKey: false, name: [ 'r' ] },
			{ note: 'F#', octave: 4, isBlackKey: true, name: [ "'" ] },
			{ note: 'G', octave: 4, isBlackKey: false, name: [ 't' ] },
			{ note: 'G#', octave: 4, isBlackKey: true, name: [ '(' ] },
			{ note: 'A', octave: 4, isBlackKey: false, name: [ 'y' ] },
			{ note: 'A#', octave: 4, isBlackKey: true, name: [ '-' ] },
			{ note: 'B', octave: 4, isBlackKey: false, name: [ 'u' ] },
			{ note: 'C', octave: 5, isBlackKey: false, name: [ 'i' ] },
			{ note: 'C#', octave: 5, isBlackKey: true, name: [ '_' ] },
			{ note: 'D', octave: 5, isBlackKey: false, name: [ 'o' ] },
			{ note: 'D#', octave: 5, isBlackKey: true, name: [ 'ç' ] },
			{ note: 'E', octave: 5, isBlackKey: false, name: [ 'p' ] },
		],
	},
];
